### ISSUE TITLE
Gpencil mode : Alt+Spacebar doesn't show popup brush menu

### ISSUE THREAD

**Issue by Bunnnyface** [tingjoybits/Brush_Manager#9]
Hi Tingjoybits,
as the title says, Alt+Spacebar shortcut doesn't show popup brush menu in Grease pencil mode.
Even if I change the shortcut to another input, or even if I change/remove the default Alt+Spacebar assign to "play in reverse".
Hope this report will help.

Thank you very much for this tremendous add-on !

**Comment by tingjoybits** [comment]
Hi. Thanks for your feedback, appreciate that. I'm not quite sure exactly what problem you are facing. The popup menus for Grease pencil should only work for Draw mode and Vertex paint. I checked for this in Blender 3.6 and 4.0 and did not find any problem. Perhaps you should specify your version of the program and the type of operating system you are using. Sometimes it happens that some addons use the same key combination and because of that there may be a conflict in the settings. Try to check how Brush manager works without other addons. If nothing helps, then provide more details on this topic, for example, you first installed this addon or after what point this problem started to occur. It is also useful to look in the console window for errors.

**Comment by Bunnnyface** [comment]
Problem solved but I can't say what was the issue exactly.
I loaded factory settings and popup now works, but I had to restore all my preferences.
Sorry for taking up your time and thank you again for this great add-on !

**Comment by tingjoybits** [comment]
No worries. I'm glad you didn't hesitate to report your difficulties and were able to resolve them. It was my pleasure to help you in any way I could. Maybe it will help someone else as well. Thanks!
